-- CreateEnum
CREATE TYPE "AuditActorType" AS ENUM ('USER', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AuditCategory" AS ENUM ('AUTHENTICATION', 'USER_ADMINISTRATION', 'COMPANY_SETTINGS', 'DEPARTMENT', 'POSITION', 'HIERARCHY', 'EMPLOYEE', 'ASSIGNMENT', 'IMPORT', 'EXPORT', 'SECURITY', 'SYSTEM');

-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('CREATED', 'UPDATED', 'ARCHIVED', 'REACTIVATED', 'ASSIGNED', 'TRANSFERRED', 'ASSIGNMENT_ENDED', 'TERMINATED', 'ROLE_CHANGED', 'USER_DISABLED', 'USER_REACTIVATED', 'USER_PROVISIONED', 'USER_LINKED_TO_EMPLOYEE', 'USER_UNLINKED_FROM_EMPLOYEE', 'SETTINGS_CHANGED', 'IMPORT_VALIDATED', 'IMPORT_EXECUTED', 'IMPORT_FAILED', 'EXPORT_REQUESTED', 'EXPORT_COMPLETED', 'EXPORT_FAILED', 'LOGIN_SUCCEEDED', 'LOGIN_REJECTED', 'UNAUTHORIZED_ACCESS_ATTEMPT');

-- CreateTable
CREATE TABLE "audit_events" (
    "id" UUID NOT NULL,
    "companyId" UUID NOT NULL,
    "actorUserId" UUID,
    "actorType" "AuditActorType" NOT NULL,
    "actorDisplayNameSnapshot" TEXT,
    "actorEmailSnapshot" TEXT,
    "action" "AuditAction" NOT NULL,
    "category" "AuditCategory" NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "entityDisplayReference" TEXT,
    "beforeData" JSONB,
    "afterData" JSONB,
    "changedFields" JSONB,
    "correlationId" TEXT,
    "importJobId" UUID,
    "exportJobId" UUID,
    "safeMetadata" JSONB,
    "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company_settings" (
    "id" UUID NOT NULL,
    "companyId" UUID NOT NULL,
    "brandingText" TEXT,
    "defaultExpansionDepth" INTEGER NOT NULL DEFAULT 2,
    "defaultViewMode" TEXT NOT NULL DEFAULT 'visual',
    "showPlannedByDefault" BOOLEAN NOT NULL DEFAULT true,
    "defaultPdfPageSize" TEXT NOT NULL DEFAULT 'A3',
    "defaultPdfLayoutMode" TEXT NOT NULL DEFAULT 'AUTO',
    "defaultPngScale" INTEGER NOT NULL DEFAULT 2,
    "includeLegendByDefault" BOOLEAN NOT NULL DEFAULT true,
    "includeConfidentialityLabelByDefault" BOOLEAN NOT NULL DEFAULT true,
    "exportRetentionDays" INTEGER NOT NULL DEFAULT 7,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "company_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "audit_events_companyId_occurredAt_idx" ON "audit_events"("companyId", "occurredAt");

-- CreateIndex
CREATE INDEX "audit_events_companyId_category_occurredAt_idx" ON "audit_events"("companyId", "category", "occurredAt");

-- CreateIndex
CREATE INDEX "audit_events_companyId_entityType_entityId_idx" ON "audit_events"("companyId", "entityType", "entityId");

-- CreateIndex
CREATE INDEX "audit_events_correlationId_idx" ON "audit_events"("correlationId");

-- CreateIndex
CREATE UNIQUE INDEX "company_settings_companyId_key" ON "company_settings"("companyId");

-- CreateIndex
CREATE UNIQUE INDEX "users_linkedEmployeeId_companyId_key" ON "users"("linkedEmployeeId", "companyId");

-- CreateIndex
CREATE UNIQUE INDEX "users_linkedEmployeeId_key" ON "users"("linkedEmployeeId");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_linkedEmployeeId_companyId_fkey" FOREIGN KEY ("linkedEmployeeId", "companyId") REFERENCES "employees"("id", "companyId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_importJobId_fkey" FOREIGN KEY ("importJobId") REFERENCES "import_jobs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_exportJobId_fkey" FOREIGN KEY ("exportJobId") REFERENCES "export_jobs"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "company_settings" ADD CONSTRAINT "company_settings_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Hand-added (not generated by Prisma — Prisma's schema DSL cannot
-- express triggers, same "hand-edit the generated migration" precedent
-- as T14's partial unique indexes): database-level immutability for
-- audit_events. This is a narrow guard against UPDATE/DELETE on an
-- already-written row, deliberately containing no business logic — see
-- docs/adr/0015-audit-event-model-and-immutability.md for why this is a
-- different (and not previously rejected) use of a trigger than the one
-- docs/adr/0008-audit-strategy.md declined (trigger-generated audit
-- entries, which DOES embed business logic and remains rejected).
CREATE OR REPLACE FUNCTION audit_events_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only: % is not permitted on this table', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_events_no_update
  BEFORE UPDATE ON "audit_events"
  FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();

CREATE TRIGGER audit_events_no_delete
  BEFORE DELETE ON "audit_events"
  FOR EACH ROW EXECUTE FUNCTION audit_events_immutable();
